# https://travis-ci.com/phoebe-project/phoebe2-workshop

# NOTE: because we checkout the branch, we may not be at this EXACT commit,
# but rather at the latest.  So re-running a travis build on and old commit
# will still update using the latest sources in the branch.  This shouldn't
# be a problem - we have the builds set to autocancel if a new push occurs
# anyways.

language: python

os: linux
dist: trusty

before_install:
  - pip install jupyter

script: |
  if [ "$TRAVIS_COMMIT_MESSAGE" != "TRAVIS: updating ipynb->py sources" ] && [ -n $GITHUB_API_KEY ]; then
    git clone --depth 1 git://github.com/phoebe-project/phoebe2-workshop.git ../phoebe2-workshop-master
    mkdir -p ../phoebe2-workshop-master/$TRAVIS_BRANCH
    jupyter nbconvert --to python ./*ipynb --output-dir=../phoebe2-workshop-master/$TRAVIS_BRANCH
    cp ./*ipynb ../phoebe2-workshop-master/$TRAVIS_BRANCH/
    cd ../phoebe2-workshop-master
    git -c user.name='travis' -c user.email='travis'
    git add $TRAVIS_BRANCH/*
    git commit -m 'TRAVIS: updating ipynb->py sources'
    git push -q -f https://kecnry:$GITHUB_API_KEY@github.com/phoebe-project/phoebe2-workshop master
  fi
