import phoebe
if phoebe.__version__ != 'workshop2021':
    raise ImportError("PHOEBE version is not workshop2021")
import numpy as np
b = phoebe.default_binary()
b.add_dataset('lc', compute_times=phoebe.linspace(0,1,5))
b.run_compute()
b.add_compute('ellc')
b.set_value_all('ld_mode', 'lookup')
b.run_compute(kind='ellc')
b.set_value('times@dataset', b.get_value('times@model'))
b.set_value('fluxes@dataset', b.get_value('fluxes@model'))
b.set_value('sigmas@dataset', np.ones_like(b.get_value('fluxes@model'))*0.01)
b.add_distribution('incl@binary', phoebe.uniform(85,90), distribution='mydist')
b.run_compute(kind='ellc', sample_from='mydist', sample_num=3)
b.add_solver('optimizer.nelder_mead', fit_parameters='incl@binary', maxiter=10, maxfev=20, solver='nm_solver')
b.run_solver('nm_solver')
b.add_solver('sampler.emcee', init_from='mydist', nwalkers=4, niters=5, solver='emcee_solver')
b.run_solver('emcee_solver', detach=True)
b.attach_job()
